name: Shepherd Productions
description: Template for a video blog.
url: 'https://www.shedpherdproductions.ga'
baseurl: 
email: jekyll-video@example.com
twitter: 
youtube: 
facebook: 
google_analytics: 'UA-00000000-1'

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video
